name: Android CI

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    name: Build Library
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle

      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          link-to-sdk: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrlibraryer
        uses: gradle/actions/wrlibraryer-validation@v4

      - name: Build Library Release
        run: ./gradlew assembleRelease

      - name: Upload release library
        uses: actions/upload-artifact@v4
        with:
          name: library-release
          path: library/build/outputs/apk/release/
